{"name": "test_create_double_user_error", "status": "passed", "description": "Попытка создать пользователя, который уже зарегистрирован посредством фмкстуры", "start": 1710229298766, "stop": 1710229299333, "uuid": "9d759024-7744-4394-ae80-09d9835a5ea8", "historyId": "b0eea2d76d8be485f545edc34842e76b", "testCaseId": "b0eea2d76d8be485f545edc34842e76b", "fullName": "tests.test_creating_user.TestCreatingUser#test_create_double_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_user"}, {"name": "subSuite", "value": "TestCreatingUser"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "15184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_user"}]}