{"name": "test_login_user_error", "status": "passed", "description": "Авторизация под неверным логином и паролем", "attachments": [{"name": "stdout", "source": "8454c975-b9e3-4677-937a-31b8410bf64b-attachment.txt", "type": "text/plain"}], "start": 1709739031174, "stop": 1709739031973, "uuid": "d87dd09d-bb6c-40dc-9a00-546809cbcfc1", "historyId": "2255ee234cfcd5d264bf7ed07b43520b", "testCaseId": "2255ee234cfcd5d264bf7ed07b43520b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "4380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}